spurs_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres  # Cambiá si usás docker o contenedor
      user: postgres
      password: postgres
      port: 5432
      dbname: nba
      schema: silver
      threads: 1
