version: 2

sources:
  - name: silver
    schema: silver
    tables:
      - name: games
      - name: players
      - name: teams 
      - name: player_stats
      - name: salaries
      - name: free_agents
      - name: injuries
      #- name: spurs_boxscores